# Generated by Django 5.1.4 on 2025-01-13 06:44

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='none', editable=False, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='title',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
